# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

development:
  adapter: mysql2
  encoding: utf8
  database: mplev_development
  pool: 5
  username: root
  password: 
test:
  adapter: mysql2
  encoding: utf8
  database: mplev_test
  pool: 5
  username: root
  password: 
production:
  adapter: mysql2
  encoding: utf8
  database: mplev_production
  pool: 5
  username: root
  password: 